/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as LogowanieRouteImport } from './routes/logowanie'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ZnajdzBiletRouteImport } from './routes/znajdz-bilet'
import { Route as StronaSlugRouteImport } from './routes/strona.$slug'
import { Route as WydarzeniaIndexRouteImport } from './routes/wydarzenia.index'
import { Route as WydarzeniaTagSlugEventSlugRouteImport } from './routes/wydarzenia.$tagSlug.$eventSlug'
import { Route as WydarzeniaTagSlugEventSlugPotwierdzenieRouteImport } from './routes/wydarzenia.$tagSlug.$eventSlug_.potwierdzenie'
import { Route as WydarzeniaTagSlugEventSlugZamowienieRouteImport } from './routes/wydarzenia.$tagSlug.$eventSlug_.zamowienie'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LogowanieRoute = LogowanieRouteImport.update({
  id: '/logowanie',
  path: '/logowanie',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ZnajdzBiletRoute = ZnajdzBiletRouteImport.update({
  id: '/znajdz-bilet',
  path: '/znajdz-bilet',
  getParentRoute: () => rootRouteImport,
} as any)
const StronaSlugRoute = StronaSlugRouteImport.update({
  id: '/strona/$slug',
  path: '/strona/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WydarzeniaIndexRoute = WydarzeniaIndexRouteImport.update({
  id: '/wydarzenia/',
  path: '/wydarzenia/',
  getParentRoute: () => rootRouteImport,
} as any)
const WydarzeniaTagSlugEventSlugRoute =
  WydarzeniaTagSlugEventSlugRouteImport.update({
    id: '/wydarzenia/$tagSlug/$eventSlug',
    path: '/wydarzenia/$tagSlug/$eventSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const WydarzeniaTagSlugEventSlugPotwierdzenieRoute =
  WydarzeniaTagSlugEventSlugPotwierdzenieRouteImport.update({
    id: '/wydarzenia/$tagSlug/$eventSlug_/potwierdzenie',
    path: '/wydarzenia/$tagSlug/$eventSlug/potwierdzenie',
    getParentRoute: () => rootRouteImport,
  } as any)
const WydarzeniaTagSlugEventSlugZamowienieRoute =
  WydarzeniaTagSlugEventSlugZamowienieRouteImport.update({
    id: '/wydarzenia/$tagSlug/$eventSlug_/zamowienie',
    path: '/wydarzenia/$tagSlug/$eventSlug/zamowienie',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/logowanie': typeof LogowanieRoute
  '/profil': typeof ProfilRoute
  '/znajdz-bilet': typeof ZnajdzBiletRoute
  '/strona/$slug': typeof StronaSlugRoute
  '/wydarzenia/': typeof WydarzeniaIndexRoute
  '/wydarzenia/$tagSlug/$eventSlug': typeof WydarzeniaTagSlugEventSlugRoute
  '/wydarzenia/$tagSlug/$eventSlug/potwierdzenie': typeof WydarzeniaTagSlugEventSlugPotwierdzenieRoute
  '/wydarzenia/$tagSlug/$eventSlug/zamowienie': typeof WydarzeniaTagSlugEventSlugZamowienieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/logowanie': typeof LogowanieRoute
  '/profil': typeof ProfilRoute
  '/znajdz-bilet': typeof ZnajdzBiletRoute
  '/strona/$slug': typeof StronaSlugRoute
  '/wydarzenia': typeof WydarzeniaIndexRoute
  '/wydarzenia/$tagSlug/$eventSlug': typeof WydarzeniaTagSlugEventSlugRoute
  '/wydarzenia/$tagSlug/$eventSlug/potwierdzenie': typeof WydarzeniaTagSlugEventSlugPotwierdzenieRoute
  '/wydarzenia/$tagSlug/$eventSlug/zamowienie': typeof WydarzeniaTagSlugEventSlugZamowienieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/logowanie': typeof LogowanieRoute
  '/profil': typeof ProfilRoute
  '/znajdz-bilet': typeof ZnajdzBiletRoute
  '/strona/$slug': typeof StronaSlugRoute
  '/wydarzenia/': typeof WydarzeniaIndexRoute
  '/wydarzenia/$tagSlug/$eventSlug': typeof WydarzeniaTagSlugEventSlugRoute
  '/wydarzenia/$tagSlug/$eventSlug_/potwierdzenie': typeof WydarzeniaTagSlugEventSlugPotwierdzenieRoute
  '/wydarzenia/$tagSlug/$eventSlug_/zamowienie': typeof WydarzeniaTagSlugEventSlugZamowienieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/logowanie'
    | '/profil'
    | '/znajdz-bilet'
    | '/strona/$slug'
    | '/wydarzenia/'
    | '/wydarzenia/$tagSlug/$eventSlug'
    | '/wydarzenia/$tagSlug/$eventSlug/potwierdzenie'
    | '/wydarzenia/$tagSlug/$eventSlug/zamowienie'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/logowanie'
    | '/profil'
    | '/znajdz-bilet'
    | '/strona/$slug'
    | '/wydarzenia'
    | '/wydarzenia/$tagSlug/$eventSlug'
    | '/wydarzenia/$tagSlug/$eventSlug/potwierdzenie'
    | '/wydarzenia/$tagSlug/$eventSlug/zamowienie'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/logowanie'
    | '/profil'
    | '/znajdz-bilet'
    | '/strona/$slug'
    | '/wydarzenia/'
    | '/wydarzenia/$tagSlug/$eventSlug'
    | '/wydarzenia/$tagSlug/$eventSlug_/potwierdzenie'
    | '/wydarzenia/$tagSlug/$eventSlug_/zamowienie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  LogowanieRoute: typeof LogowanieRoute
  ProfilRoute: typeof ProfilRoute
  ZnajdzBiletRoute: typeof ZnajdzBiletRoute
  StronaSlugRoute: typeof StronaSlugRoute
  WydarzeniaIndexRoute: typeof WydarzeniaIndexRoute
  WydarzeniaTagSlugEventSlugRoute: typeof WydarzeniaTagSlugEventSlugRoute
  WydarzeniaTagSlugEventSlugPotwierdzenieRoute: typeof WydarzeniaTagSlugEventSlugPotwierdzenieRoute
  WydarzeniaTagSlugEventSlugZamowienieRoute: typeof WydarzeniaTagSlugEventSlugZamowienieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logowanie': {
      id: '/logowanie'
      path: '/logowanie'
      fullPath: '/logowanie'
      preLoaderRoute: typeof LogowanieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/znajdz-bilet': {
      id: '/znajdz-bilet'
      path: '/znajdz-bilet'
      fullPath: '/znajdz-bilet'
      preLoaderRoute: typeof ZnajdzBiletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strona/$slug': {
      id: '/strona/$slug'
      path: '/strona/$slug'
      fullPath: '/strona/$slug'
      preLoaderRoute: typeof StronaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wydarzenia/': {
      id: '/wydarzenia/'
      path: '/wydarzenia'
      fullPath: '/wydarzenia/'
      preLoaderRoute: typeof WydarzeniaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wydarzenia/$tagSlug/$eventSlug': {
      id: '/wydarzenia/$tagSlug/$eventSlug'
      path: '/wydarzenia/$tagSlug/$eventSlug'
      fullPath: '/wydarzenia/$tagSlug/$eventSlug'
      preLoaderRoute: typeof WydarzeniaTagSlugEventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wydarzenia/$tagSlug/$eventSlug_/potwierdzenie': {
      id: '/wydarzenia/$tagSlug/$eventSlug_/potwierdzenie'
      path: '/wydarzenia/$tagSlug/$eventSlug/potwierdzenie'
      fullPath: '/wydarzenia/$tagSlug/$eventSlug/potwierdzenie'
      preLoaderRoute: typeof WydarzeniaTagSlugEventSlugPotwierdzenieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wydarzenia/$tagSlug/$eventSlug_/zamowienie': {
      id: '/wydarzenia/$tagSlug/$eventSlug_/zamowienie'
      path: '/wydarzenia/$tagSlug/$eventSlug/zamowienie'
      fullPath: '/wydarzenia/$tagSlug/$eventSlug/zamowienie'
      preLoaderRoute: typeof WydarzeniaTagSlugEventSlugZamowienieRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  LogowanieRoute: LogowanieRoute,
  ProfilRoute: ProfilRoute,
  ZnajdzBiletRoute: ZnajdzBiletRoute,
  StronaSlugRoute: StronaSlugRoute,
  WydarzeniaIndexRoute: WydarzeniaIndexRoute,
  WydarzeniaTagSlugEventSlugRoute: WydarzeniaTagSlugEventSlugRoute,
  WydarzeniaTagSlugEventSlugPotwierdzenieRoute:
    WydarzeniaTagSlugEventSlugPotwierdzenieRoute,
  WydarzeniaTagSlugEventSlugZamowienieRoute:
    WydarzeniaTagSlugEventSlugZamowienieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
