/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogowanieRouteImport } from './routes/logowanie'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ZnajdzBiletRouteImport } from './routes/znajdz-bilet'
import { Route as StronaSlugRouteImport } from './routes/strona.$slug'
import { Route as WydarzeniaIndexRouteImport } from './routes/wydarzenia.index'
import { Route as WydarzeniaSlugRouteImport } from './routes/wydarzenia.$slug'
import { Route as WydarzeniaSlugPotwierdzenieRouteImport } from './routes/wydarzenia.$slug_.potwierdzenie'
import { Route as WydarzeniaSlugZamowienieRouteImport } from './routes/wydarzenia.$slug_.zamowienie'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogowanieRoute = LogowanieRouteImport.update({
  id: '/logowanie',
  path: '/logowanie',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ZnajdzBiletRoute = ZnajdzBiletRouteImport.update({
  id: '/znajdz-bilet',
  path: '/znajdz-bilet',
  getParentRoute: () => rootRouteImport,
} as any)
const StronaSlugRoute = StronaSlugRouteImport.update({
  id: '/strona/$slug',
  path: '/strona/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WydarzeniaIndexRoute = WydarzeniaIndexRouteImport.update({
  id: '/wydarzenia/',
  path: '/wydarzenia/',
  getParentRoute: () => rootRouteImport,
} as any)
const WydarzeniaSlugRoute = WydarzeniaSlugRouteImport.update({
  id: '/wydarzenia/$slug',
  path: '/wydarzenia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WydarzeniaSlugPotwierdzenieRoute =
  WydarzeniaSlugPotwierdzenieRouteImport.update({
    id: '/wydarzenia/$slug_/potwierdzenie',
    path: '/wydarzenia/$slug/potwierdzenie',
    getParentRoute: () => rootRouteImport,
  } as any)
const WydarzeniaSlugZamowienieRoute =
  WydarzeniaSlugZamowienieRouteImport.update({
    id: '/wydarzenia/$slug_/zamowienie',
    path: '/wydarzenia/$slug/zamowienie',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logowanie': typeof LogowanieRoute
  '/profil': typeof ProfilRoute
  '/znajdz-bilet': typeof ZnajdzBiletRoute
  '/strona/$slug': typeof StronaSlugRoute
  '/wydarzenia/$slug': typeof WydarzeniaSlugRoute
  '/wydarzenia/': typeof WydarzeniaIndexRoute
  '/wydarzenia/$slug/potwierdzenie': typeof WydarzeniaSlugPotwierdzenieRoute
  '/wydarzenia/$slug/zamowienie': typeof WydarzeniaSlugZamowienieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logowanie': typeof LogowanieRoute
  '/profil': typeof ProfilRoute
  '/znajdz-bilet': typeof ZnajdzBiletRoute
  '/strona/$slug': typeof StronaSlugRoute
  '/wydarzenia/$slug': typeof WydarzeniaSlugRoute
  '/wydarzenia': typeof WydarzeniaIndexRoute
  '/wydarzenia/$slug/potwierdzenie': typeof WydarzeniaSlugPotwierdzenieRoute
  '/wydarzenia/$slug/zamowienie': typeof WydarzeniaSlugZamowienieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logowanie': typeof LogowanieRoute
  '/profil': typeof ProfilRoute
  '/znajdz-bilet': typeof ZnajdzBiletRoute
  '/strona/$slug': typeof StronaSlugRoute
  '/wydarzenia/$slug': typeof WydarzeniaSlugRoute
  '/wydarzenia/': typeof WydarzeniaIndexRoute
  '/wydarzenia/$slug_/potwierdzenie': typeof WydarzeniaSlugPotwierdzenieRoute
  '/wydarzenia/$slug_/zamowienie': typeof WydarzeniaSlugZamowienieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logowanie'
    | '/profil'
    | '/znajdz-bilet'
    | '/strona/$slug'
    | '/wydarzenia/$slug'
    | '/wydarzenia/'
    | '/wydarzenia/$slug/potwierdzenie'
    | '/wydarzenia/$slug/zamowienie'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logowanie'
    | '/profil'
    | '/znajdz-bilet'
    | '/strona/$slug'
    | '/wydarzenia/$slug'
    | '/wydarzenia'
    | '/wydarzenia/$slug/potwierdzenie'
    | '/wydarzenia/$slug/zamowienie'
  id:
    | '__root__'
    | '/'
    | '/logowanie'
    | '/profil'
    | '/znajdz-bilet'
    | '/strona/$slug'
    | '/wydarzenia/$slug'
    | '/wydarzenia/'
    | '/wydarzenia/$slug_/potwierdzenie'
    | '/wydarzenia/$slug_/zamowienie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogowanieRoute: typeof LogowanieRoute
  ProfilRoute: typeof ProfilRoute
  ZnajdzBiletRoute: typeof ZnajdzBiletRoute
  StronaSlugRoute: typeof StronaSlugRoute
  WydarzeniaSlugRoute: typeof WydarzeniaSlugRoute
  WydarzeniaIndexRoute: typeof WydarzeniaIndexRoute
  WydarzeniaSlugPotwierdzenieRoute: typeof WydarzeniaSlugPotwierdzenieRoute
  WydarzeniaSlugZamowienieRoute: typeof WydarzeniaSlugZamowienieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logowanie': {
      id: '/logowanie'
      path: '/logowanie'
      fullPath: '/logowanie'
      preLoaderRoute: typeof LogowanieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/znajdz-bilet': {
      id: '/znajdz-bilet'
      path: '/znajdz-bilet'
      fullPath: '/znajdz-bilet'
      preLoaderRoute: typeof ZnajdzBiletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strona/$slug': {
      id: '/strona/$slug'
      path: '/strona/$slug'
      fullPath: '/strona/$slug'
      preLoaderRoute: typeof StronaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wydarzenia/': {
      id: '/wydarzenia/'
      path: '/wydarzenia'
      fullPath: '/wydarzenia/'
      preLoaderRoute: typeof WydarzeniaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wydarzenia/$slug': {
      id: '/wydarzenia/$slug'
      path: '/wydarzenia/$slug'
      fullPath: '/wydarzenia/$slug'
      preLoaderRoute: typeof WydarzeniaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wydarzenia/$slug_/potwierdzenie': {
      id: '/wydarzenia/$slug_/potwierdzenie'
      path: '/wydarzenia/$slug/potwierdzenie'
      fullPath: '/wydarzenia/$slug/potwierdzenie'
      preLoaderRoute: typeof WydarzeniaSlugPotwierdzenieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wydarzenia/$slug_/zamowienie': {
      id: '/wydarzenia/$slug_/zamowienie'
      path: '/wydarzenia/$slug/zamowienie'
      fullPath: '/wydarzenia/$slug/zamowienie'
      preLoaderRoute: typeof WydarzeniaSlugZamowienieRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogowanieRoute: LogowanieRoute,
  ProfilRoute: ProfilRoute,
  ZnajdzBiletRoute: ZnajdzBiletRoute,
  StronaSlugRoute: StronaSlugRoute,
  WydarzeniaSlugRoute: WydarzeniaSlugRoute,
  WydarzeniaIndexRoute: WydarzeniaIndexRoute,
  WydarzeniaSlugPotwierdzenieRoute: WydarzeniaSlugPotwierdzenieRoute,
  WydarzeniaSlugZamowienieRoute: WydarzeniaSlugZamowienieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
